name: Selenium Regression Tests

on:
  push:
    branches: [ main ]  # Se corre cada vez que subes código
  schedule:
    - cron: '0 0 * * *' # Opcional: Se corre todas las noches a las 00:00

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar Tests con Pytest
      run: |
        pytest --alluredir=allure-results
      continue-on-error: true # Permite que el reporte se genere aunque falle un test

    - name: Generar Reporte Allure
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results
        allure_history: allure-history

    - name: Publicar Reporte en GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: allure-history